### PR TITLE
Integrate some changes?

### PR DESCRIPTION
**Pull request by mildlygeeky**
Hey! This is a great tool — thanks for making it.

I made some changes that I think could make it better:
- Pulled config.js out of source control (renamed to config.js.example) so that it can be updated down the road if need be. Also updated the README to reflect this.
- Added the US JSON URLs to config.js.example in the comments
- Added fuller descriptions to the iphone-models.js file so that users can know which carrier each model number is for (as you need to know the carrier to know which model applied to you).

I haven't made this change, but one more improvement (especially for US users) would be to be able to specify store IDs in config.js — the US is so big that it isn't going to help me to know that a model is in stock 3,000 miles away.

It would be great if you could provide config.js just the stores you want to check. Right now I've been using my own manual stores.json file that has been reduced down to just my local stores, but it would be great if it could be done without that hack.

Again, thank you for writing this! I had a manual PHP / Twilio script that I was using for this, but yours is a far more comprehensive solution.

### CODE REVIEW

**Comment by mildlygeeky** [comment]
Also, you may want to consider adding a note on using `forever` to run this — I had it stop running on me a couple times, and now have it running constantly with `forever`.

**Comment by TomThorpe** [comment]
Great additions - thanks! 

You're right about the stores, I did think about that while I was writing it but didnt get around to adding it (as you suspected, its not much of an issue here in the UK, but yeah I can definitely see it being an issue for the USA. I like your fix of manually filtering the stores json though for now)

Do you know why it stopped on you a few times? Mine has been running for a few days now and is still going. forever is a good idea though so I'll add a note about that.

**Comment by mildlygeeky** [comment]
Glad you like the tweaks!

Not sure why it stopped running — the process ID was still out there, but it wasn't outputting anything (was writing to a file to capture output after the first time it happened). I'm not an expert node user (typically using it for Gulp build tools on web projects), so not sure of the best way to debug - sorry!

**Comment by TomThorpe** [comment]
No worries - I'll look out for it happening to me. Thanks again!

**Pull request merged**
